### ISSUE TITLE
Auto reload when file is modified on server

### ISSUE THREAD

**Issue by natilux2** [petrsvihlik/WopiHost#100]
How can I reflect change to client when file is modified on server

**Comment by petrsvihlik** [comment]
There is no built-in functionality in WOPI to facilitate this. 

One way to do it would be establishing a connection between the server and the client's [host page](https://wopi.readthedocs.io/en/latest/hostpage.html) using e.g. [SignalR](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client). 
The server could watch for changes (e.g. using the [`FileSystemWatcher`](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesystemwatcher) in case of local file storage based on `System.IO.`) and send messages to the client indicating that the file has changed and a reload is in order.

However, if there are two systems accessing the same files at the same time, I'd strongly recommend implementing file locking and shared lock storage to avoid any R/W conflicts.

If you use `System.IO`, I'd also recommend reviewing and tuning the `FileMode`, `FileAccess`, and `FileShare` properties of [`FileStream`](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.-ctor?view=netcore-3.1#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_IO_FileAccess_System_IO_FileShare_) to minimize the risk of running into problems with conflicting streams.
