### ISSUE TITLE
"camelCase" formatting seems to cause problems with "Office for the web" as client

### ISSUE THREAD

**Issue by planax** [petrsvihlik/WopiHost#123]
https://github.com/petrsvihlik/WopiHost/blob/842e6ff132716afc087a16f1e215ec74c93fae46/WopiHost.Core/Controllers/FilesController.cs#L78

For me, when using .NET 5/Core 3.1, the response will contain JSON key names formatted in camelCase. This seems to be the new default.

```json
{
  "baseFileName": "TestDocument.docx",
  "ownerId": "uid-12345-6789",
  "size": 1234567,
  "userId": "uid-12345-6789",
  "version": "1234567"
}
```

This wouldn't be per se a problem, but when using **Office for the web** as Wopi Client, no _GetFile_ will be sent back. After quite some time reading the [MS-WOPI protocol specification, part 3.3.5.1.2.2](https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-wopi/71e66fb4-144b-4369-b597-f425f0b700b9), I realized that this was the reason.

I fixed the issue by forcing PascalCase, which seems to be what [MS-WOPI](https://docs.microsoft.com/en-us/openspecs/office_protocols/ms-wopi) expects.

Before:
https://github.com/petrsvihlik/WopiHost/blob/842e6ff132716afc087a16f1e215ec74c93fae46/WopiHost/Startup.cs#L44

After:
```csharp
services.AddControllers()
  .AddNewtonsoftJson(options =>
  {
      options.SerializerSettings.ContractResolver = new DefaultContractResolver();
  });
```

Response:
```json
{
  "BaseFileName": "TestDocument.docx",
  "OwnerId": "uid-12345-6789",
  "Size": 1234567,
  "UserId": "uid-12345-6789",
  "Version": "1234567"
}
```

**Comment by petrsvihlik** [comment]
Thank you for reporting this @planax , I'll try to reproduce it next week and let you know!

**Comment by planax** [comment]
@petrsvihlik, this can be closed. It was actually my fault. I didn't notice you were specifying PascalCase formatting in WopiCoreBuilderExtensions class.
