### ISSUE TITLE
Possibility to periodically refresh discovery information

### ISSUE THREAD

**Issue by planax** [petrsvihlik/WopiHost#130]
**Motivation**
According to the official documentation WOPI Host should refresh the discovery information each 12 to 24 hours as action URLs can change when Microsoft introduce breaking changes. This is only valid for Office for the web implementations.

More info: https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/discovery

**Comment by petrsvihlik** [comment]
@planax good point...what would you recommend using for the cache? I would rather avoid using `MemoryCache` for a single object.

This seems like a good choice to me:

https://www.strathweb.com/2016/11/lazy-async-initialization-for-expiring-objects/

**Comment by petrsvihlik** [comment]
can be now configured via:
https://github.com/petrsvihlik/WopiHost/blob/master/WopiHost.Discovery/DiscoveryOptions.cs

an example:

https://github.com/petrsvihlik/WopiHost/blob/61fb2322342d69104525675b55bdd367ff076025/WopiHost.Web/appsettings.json#L10
