### ISSUE TITLE
Set up code coverage on comit

### ISSUE THREAD

**Issue by petrsvihlik** [petrsvihlik/WopiHost#25]
Set up on of the following:
- https://codecov.io/
- https://coveralls.io/
- https://scan.coverity.com/
- https://sonarqube.com/about

1. Download [OpenCover](https://github.com/OpenCover/opencover)
2. Run OpenCover
3. Upload OpenCover's results

running opencover with .net core:
- official example: https://github.com/codecov/example-csharp

example of opencover with dotnet cli:
http://stackoverflow.com/questions/36460254/vs2015-code-coverage-not-working-with-tests-in-asp-net-core-1-0-formerly-known

working code:
`OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:" test ""C:\Users\petrs\Documents\GitHub\WopiHost\WopiHost.FileSystemProvider.Tests\project.json"" -f netcoreapp1.0 -xml ""C:\Users\petrs\Documents\GitHub\WopiHost\WopiHost.FileSystemProvider.Tests\xunit-results.xml"" -nologo -parallel none" -output:"C:\Users\petrs\Documents\GitHub\WopiHost\coverage.xml" -register:user -filter:"+[*]* -[xunit*]* -[*]*Migrations.*" -returntargetcode -oldstyle`

`-oldstyle` argument [required](https://github.com/OpenCover/opencover/issues/601) until https://github.com/OpenCover/opencover/issues/595 gets implemented

[another example that should work](https://github.com/OpenCover/opencover/issues/601#issuecomment-241375834):
`c:\Users\tmds\AppData\Local\Apps\OpenCover\OpenCover.Console.exe "-target:C:\Program Files\dotnet\dotnet.exe" -targetargs:test -register:user -filter:"+[*]* -[xunit*]*" -output:coverage.xml -oldStyle`

opencover+appveyor example:
https://github.com/jwaliszko/ExpressiveAnnotations

other resources:
https://github.com/OpenCover/opencover/wiki/DNX-Support
http://blog.stephencleary.com/2015/03/continuous-integration-code-coverage-open-source-net-coreclr-projects.html
http://dotnetthoughts.net/measuring-code-coverage-of-aspnet-core-applications-using-opencover/
http://help.appveyor.com/discussions/problems/4394-problem-with-args-to-xunit-in-powershell
https://github.com/OpenCover/opencover/issues/327

Full YMLs:
- https://anotherlookontech.wordpress.com/2016/10/12/integrate-net-core-appveyor-opencover-and-codecov/
-- https://github.com/joaoasrosa/unittestsexternalsources/blob/master/appveyor.yml
- https://blog.markvincze.com/setting-up-coveralls-for-a-net-core-project/ 
-- https://github.com/markvincze/Stubbery/blob/master/coverage.sh
- http://blog.stephencleary.com/2015/03/continuous-integration-code-coverage-open-source-net-coreclr-projects.html

**Comment by petrsvihlik** [comment]
working sample:
https://github.com/OpenCover/opencover/issues/601#issuecomment-245453144
http://stackoverflow.com/questions/36460254/vs2015-code-coverage-not-working-with-tests-in-asp-net-core-1-0-formerly-known/39324025#39324025

**Comment by olivif** [comment]
@petrsvihlik `-oldstyle` did the trick for me, thank you for saving me hours of my life.

**Comment by petrsvihlik** [comment]
@olivif no problem :)

the functionality has been implemented in [appveyor.yml](https://github.com/petrsvihlik/WopiHost/blob/master/appveyor.yml), the results are here: https://codecov.io/gh/petrsvihlik/WopiHost
