### ISSUE TITLE
How and where can I get the WOPI Client (Office web app server) error logs

### ISSUE THREAD

**Issue by soumyaansh** [petrsvihlik/WopiHost#29]
Hi petrsvihlik, my issue is rather related to a general problem then to your source code, I am sorry if you didn't like me raising this question as an issue. I found you most active on WOPI platform.

I have implemented the WOPI Host and client on Windows Server 2012 RC, I can access the discovery url but when I am trying to open a office file on the browser, the file is not getting load.

I can see the logs of WOPI Host but how can I see the WOPI Client error logs ? when I further investigated I found in the IIS Administrator tools under event viewer there are lots of error logs related to Office Web Apps Server and all are showing "Reported Status :Machine Health is UnHealthy".

Please let me know if you have any idea on this issue.

**Comment by petrsvihlik** [comment]
hi, i'll get back to you next week. i'm out of office until the 25th. thanks for understanding

**Comment by soumyaansh** [comment]
ok, thanks a lot for the follow up.

**Comment by petrsvihlik** [comment]
I'd do several things:
- debug the WOPI Host to verify that it's not throwing any exceptions
- check the requests and responses with fiddler to find out when it fails (https://wopi.readthedocs.org/en/latest/build_test_ship/troubleshooting.html)
- check the event viewer of the WOPI client machine to see any potential errors
