### ISSUE TITLE
Error during Opening the url of edit document

### ISSUE THREAD

**Issue by karunkumar009** [petrsvihlik/WopiHost#37]
I am trying to open the docx file but I am not able to render it

http://ussecvmfsu3j9.ey.net:8080/wv/wordviewerframe.aspx?WOPISrc=http%3a%2f%2fussecvmfsu3j9.ey.net%3a8080%2fapi%2fwopi%2ffiles%2ftest.docx&access_token=8OH4q2yWjZM%3dzfE7tZ94cGYRWC%2bDCUYrwJpg6FodQtXVluxjRVoFTLs%3d

and the window with word online keeps loading

Can anybody suggest me how to make it render on browser?

Thanks in advance

**Comment by petrsvihlik** [comment]
Hi. I'll look into it next week...

**Comment by karunkumar009** [comment]
http://ussecvmfsu3j9.ey.net:8080/p/PowerPointFrame.aspx?WOPISrc=http%3a%2f%2flocalhost%3a32875%2fapi%2ffiles%2ftest.pptx&access_token=%2bX%2bDE1XD%2bcY%3dnphja%2bgAJl7p%2fzMBum4oiX1Atw6KoWhot1j%2fEUnuDYw%3d

WOPISRC value will be localhost or wopiserver url value.?

Above example is for powerpont.
Please look into this asap.

Thank you.

**Comment by petrsvihlik** [comment]
Regarding the URL, unless you are running the wopi host and wopi client (owa) on the same server, you have to use something different than "localhost" (so in your case the URL in the first comment looks more likely). hostname of your wopi host application has to be accessible from the wopi client machine. (you can try debugging a simple checkfileinfo request).

anyway, if you are still unable to resolve the issue, we'll need more information...

1. Which version of OWA are you using? Office Web Apps 2013 or Office Online Server 2016? (The latest version should work with both)
2. Can you look at the windows event viewer for possible errors from OWA?
3. Can you inspect the log files? https://blogs.msdn.microsoft.com/zwsong/2013/04/16/where-would-you-find-uls-logs-on-office-web-apps-owa-2013-server/ Use the correlation id to match records related to your editing session.
