### ISSUE TITLE
Can't edit word file, open pdf file

### ISSUE THREAD

**Issue by huanbd** [petrsvihlik/WopiHost#42]
Hi ,
I create a WOPI Host project in .NET 4.6 base on your project .NET Core, 
but I can't edit word file and open pdf file. 
Can you help me to find the problem. I think, the problem is Cobalt implementation or setting in Office Web App Server
I've converted to Web API2, It work completely with exel, powpoint, and only view word
WOPI Client is Office Web App Server 2013 SP1
When edit word file, browser show file can not be open, I debug and see that It hasn't exist exception

Thank you,

**Comment by petrsvihlik** [comment]
Hi Huan, I can't really help you unless you put sources of your converted project to GitHub and share more details about the errors you are getting (OWA log, windows event viewer, etc.)

**Comment by huanbd** [comment]
Hi Petrsvihlik,

I've just uploaded my project to GitHub https://github.com/huanbd/wopi_host
I've checked OWA log, and window event but It  hasn't existed error
and I've got code from https://github.com/marx-yu/WopiHost branch of release_0.8_for_owa2013, and It's successfully edit word office file
So I think, It's not problem of OWA enviroment. In Marx-yu's sample, he has used Response object of HttpListener, but in my sample api I use HttpResponseMessage.
In the first time, I haven't believed it. So I was created sample web api and copy all code from Marx-yu's sample, and the sample api wasn't run
So my main concern is HttpResponseMessage in web api, I'm still finding the solution, but not yet find out

Please help me discover this problem, 
thank you,

**Comment by petrsvihlik** [comment]
Debug the responses using Fiddler and check what does your application actually return. I bet the problem is something as simple as a stream not being rewound. Try calling `stream.Seek(0, SeekOrigin.Begin);` (on your MemoryStream).

**Comment by huanbd** [comment]
Hi Petrsvihlik,

I try seek stream and it run successfully :D

Thank you for your help,

Best wish for you!

Huanbd,

Sincerely,

Get Outlook for Android

________________________________
