### ISSUE TITLE
How to set file limit OOS?

### ISSUE THREAD

**Issue by wjw0716** [petrsvihlik/WopiHost#47]
for example,the docx file limit is 50MB.

I'm so sorry that my Enlish is poor.

Thank you.

**Comment by petrsvihlik** [comment]
Hi @wjw0716 , I'm not exactly sure what you are asking about.

Perhaps this? The FilesController is checking whether the file is not larger than the value specified by the X-WOPI-MaxExpectedSize header:

https://github.com/petrsvihlik/WopiHost/blob/master/WopiHost.Core/Controllers/FilesController.cs#L113

Feel free to join the chat here: https://gitter.im/ms-wopi/Lobby
