### ISSUE TITLE
hi @petrsvihlik

### ISSUE THREAD

**Issue by welon2005** [petrsvihlik/WopiHost#49]
I'm run your project in my PC very well, but WopiHost show message like this:
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
System.FormatException: The input is not a valid Base-64 string as it contains a
 non-base 64 character, more than two padding characters, or an illegal characte
r among the padding characters.
   at System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, B
yte* startDestPtr, Int32 destLength)
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at WopiHost.FileSystemProvider.WopiFileSystemProvider.DecodeIdentifier(String
 identifier) in D:\WopiHost-master(4)\WopiHost-master\WopiHost.FileSystemProvide
r\WopiFileSystemProvider.cs:line 97
   at WopiHost.FileSystemProvider.WopiFileSystemProvider.GetWopiFile(String iden
tifier) in D:\WopiHost-master(4)\WopiHost-master\WopiHost.FileSystemProvider\Wop
iFileSystemProvider.cs:line 47
   at WopiHost.Core.Controllers.FilesController.<GetCheckFileInfo>d__11.MoveNext
() in D:\WopiHost-master(4)\WopiHost-master\WopiHost.Core\Controllers\FilesContr
oller.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMet
hodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActio
nFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionEx
ecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next
, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__
20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__
18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>
d__7.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1040.8624ms 500 text/html; charset=utf-8

It may possibly cannot support file with chinese character filename ???
i have file named chinese character filename in wopi-docs.

How to support chinese character filename  ?

**Comment by petrsvihlik** [comment]
The [default implementation](C:\Users\petrs\Documents\GitHub\WopiHost\WopiHost.FileSystemProvider\WopiFileSystemProvider.cs) expects the identifier to be encoded in bas64. (This allows having slashes in the path and therefore support subfolders.)

Use the following method (in WopiFileSystemProvider) to encode your path:
```
private string EncodeIdentifier(string path)
		{
			var bytes = Encoding.UTF8.GetBytes(path);
			return Convert.ToBase64String(bytes);
		}
```

or adjust WopiFileSystemProvider to your needs

OR implement a custom `IWopiStorageProvider`.

If you have any questions, let's discuss them in the gitter room: https://gitter.im/ms-wopi/
