### ISSUE TITLE
Implement Co-authoring

### ISSUE THREAD

**Issue by petrsvihlik** [petrsvihlik/WopiHost#5]
Accordingly to MS-FSSHTTP

Specification: 
http://wopi.readthedocs.io/en/latest/scenarios/coauth.html
https://msdn.microsoft.com/en-us/library/hh622920(v=office.12).aspx

[Per their clarification, MS-FSSHTTP is required for Word editing of any kind; Locks are not enough.](http://msdn.developer-works.com/article/11894745/MS-WOPI+and+relation+to+MS-FSSHTTP)

**Comment by Robban1980** [comment]
@petrsvihlik might be the wrong place to ask, is Cobalt / MS-FSSHTTP a dead protocol or just no need for improvements? Been studying the topic for a while and learning about it to try to do an implementation (huge project).

**Comment by petrsvihlik** [comment]
Hi @Robban1980,
I'm not sure if it's dead but one thing's for sure - Office Online doesn't require Cobalt for co-authoring. There's no mention of it in the [docs](https://docs.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/scenarios/coauth) so the cloud version of Office can definitely live without it.

I think the best place to ask this question is: https://github.com/microsoft/Office-Online-Test-Tools-and-Documentation/issues

Feel free to tag me there, I'm also interested in the answer from the team :)
