### ISSUE TITLE
can't view word but can edit 

### ISSUE THREAD

**Issue by sweetwxh** [petrsvihlik/WopiHost#52]
Have you ever met this issue?
Excel can be viewed and edited. Word can't (not all files, some  can be viewed )， all of them are editable though.I'm wondering if this bug was caused by oos server?

**Comment by petrsvihlik** [comment]
Hi @sweetwxh ,
that's interesting. 
- have you checked the windows event viewer of the server where the OOS runs? there should be a separate log just for OOS/OWA...
- is the wopi host throwing any errors? can you debug it?
- can you share the files here? for testing purposes...

**Comment by sweetwxh** [comment]
@petrsvihlik thanks for your replay. 
Maybe it's a bug of oos.  I have solved this problem by downloading a newer version of oos.
But do you know how to validate a file was opened by an authenticated user? I use your code to host files, the url created for authenticated user can be shared to other one(with the same token). I've no idea how to limit the url that only be used by the same user who created the token. Do you have any suggestion? tks.

**Comment by petrsvihlik** [comment]
1) you should never include access_token in the url for production purposes...that's one security precaution. so in my sample app, use the approach demonstrated in HomeController.Detail and in the documentation (http://wopi.readthedocs.io/en/latest/hostpage.html?highlight=frame) -> store the token in a hidden field `<input name="access_token" value="<ACCESS_TOKEN_VALUE>" type="hidden"/>`
the DIRECT EDIT LINK in the sample is there just for debugging purposes

2) the token is [scoped to a single user and resource combination](scoped to a single user and resource combination). you should take that into account when implementing the `IWopiSecurityHandler`. but if the token is compromised, anyone can access the file. your job is to make sure the token doesn't get compromised.

3) you can use [access_token_ttl](http://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-access-token-ttl) to require the WOPI client to refresh user sessions after some time

**Comment by sweetwxh** [comment]
Thanks, @petrsvihlik. I'll have a try.
