### ISSUE TITLE
Where to download the client discovery XML from for Office Online WOPI Client?

### ISSUE THREAD

**Issue by Sathyaish** [petrsvihlik/WopiHost#53]
First of all, very nice. Thank you so much. Your project is very helpful for me.

I see that you have the client discovery XML for Office Online inside your discovery tests and you're probably using your `FileSystemDiscoveryProvider` (or some such) to load the downloaded file.

But if I need to use your `HttpDiscoveryProvider` to get the XML from the Web, at what URL may I find the client discovery XML file for Office Online?

You may answer the question here or on StackOverflow or both.

My question is: https://stackoverflow.com/questions/45429487/from-where-may-i-get-the-wopi-client-discovery-xml-for-the-wopi-client-office-on

Permalink: https://stackoverflow.com/q/45429487/303685

Once more, thanks for such a wonderful effort.

**Comment by petrsvihlik** [comment]
Hi, I answered your question on SO.
To add a bit more context, have a look at how the discovery URL [is built](https://github.com/petrsvihlik/WopiHost/blob/8ee5d23f7d2baa56e676f16d9fa3ef257c0349be/WopiHost.Discovery/HttpDiscoveryFileProvider.cs#L23) in this project. So the only thing you need to provide in the setting is the base URL of the OWA server.

**Comment by Sathyaish** [comment]
Thank you. I saw the two implementations (the file based one and this Http one you're referring to) before posting the question. Nice work. Neat.
