### ISSUE TITLE
Running the application Problem

### ISSUE THREAD

**Issue by amiradib** [petrsvihlik/WopiHost#54]
navigate to the WopiHost folder and run 

`dotnet run `

but i get 
 Project file does not exist '...\WopiHost-master1\WopiHost\project.json' error.

**Comment by petrsvihlik** [comment]
Apparently, you are using an older dotnet tooling because it searches for a project.json. Project.json files have been replaced by .csproj files in .NET Core 1.0 RTM. You have to install .NET Core 1.0 RTM SDK or newer. Ideally, install VS 2017.
