### ISSUE TITLE
How to remove cobalt

### ISSUE THREAD

**Issue by lan-nguyen91** [petrsvihlik/WopiHost#55]
Sorry i am new to C# development,

I try to get this project built and run into a cobalt error.
I don't know how to remove the reference according to the README.

Can someone give a direction to disable cobalt please.

Thanks

**Comment by petrsvihlik** [comment]
Just remove `<ProjectReference Include="..\WopiHost.Cobalt\WopiHost.Cobalt.csproj" />` from WopiHost.csproj (Right-click WopiHost.csproj -> Edit WopiHost.csproj in Visual Studio). 

Optionally, remove the whole WopiHost.Cobalt project from the solution. (Right-click the project -> Remove in Visual Studio)
