### ISSUE TITLE
Not Working for cobaltCore v16.0.6607.1200 and dotnet core 2

### ISSUE THREAD

**Issue by samnoon** [petrsvihlik/WopiHost#58]
I have download the code and try to run but getting error.
i am using vs2017. cobaltCore v16.0.6607.1200 and dotnet core 2
can you please have a look into this. i need a bootstrap into it.

Thanks

**Comment by petrsvihlik** [comment]
hi @samnoon , yes, support of cobalt v16.* is in the backlog #38 . 
currently, i don't have capacity to look into it. there are some major changes in the dll that need a lot of further refactoring. 

eta: somewhere in the H1/2018.

i'd be glad if someone could help with this issue.
