### ISSUE TITLE
About configuration

### ISSUE THREAD

**Issue by mohebbo** [petrsvihlik/WopiHost#59]
WopiFileProviderAssemblyName - name of assembly containing implementation of WopiHost.Abstractions interfaces

What should be the interface name? Should i need to implement this? if so do u have any sample implementation

WopiRootPath - provider-specific setting used by WopiFileSystemProvider (which is an implementation of IWopiFileProvider working with System.IO)

WopiRootPath : what will be the root path? is it the file location? 

server.urls - hosting URL(s) used by Kestrel. Read more...

is it possible to share a sample configuration with necessary implementation class so that i can run the sample,

thanks

**Comment by petrsvihlik** [comment]
I'll update the documentation next week and add sample configuration values.

thanks for your suggestion @mohebbo

**Comment by brecollog** [comment]
Does anyone have any samples for these configuration items? I would love to be able to run this sample app but the WebHost throws an error b/c of the inability to find a provider name for the WopiHost.Abstractions.  What is needed to this operable? Thanks!

**Comment by petrsvihlik** [comment]
@brecollog sorry, I didn't have much time for this project lately. I'll try to update the documentation this week.

**Comment by unejamardiani** [comment]
I have the same issue, can anyone help me, please? Thanks!

**Comment by puppetSpace** [comment]
I have the same issue. I wanted to try it. But configuration is missing.

**Comment by poneymusical** [comment]
Just add `"WopiFileProviderAssemblyName": "WopiHost.FileSystemProvider"` in WopiHost's appsettings.json.

**Comment by SimonCropp** [comment]
any update on this?

**Comment by petrsvihlik** [comment]
Hi @SimonCropp . I'll do my best to finally do update the docs this week. I keep postponing it for months and I'm not proud of that :(
Hopefully, I'll have some more time this summer to add some more features.

**Comment by petrsvihlik** [comment]
Hey @mohebbo , @brecollog , @unejamardiani , @poneymusical , @puppetSpace , @SimonCropp !

Sorry it took so long, here's the updated documentation: https://github.com/petrsvihlik/WopiHost/blob/master/README.md#configuration

Hopefully, I'll be spending much more time on this project from now on. I have whole October dedicated for it. 

Let me know what other issues you are facing and let's tackle them together. 

Thanks and sorry again"

**Comment by petrsvihlik** [comment]
I'd be glad to chat with you about WOPI real-time at https://gitter.im/ms-wopi/Lobby#
