### ISSUE TITLE
Edit in native MS Office apps on Windows.

### ISSUE THREAD

**Issue by AKlaus** [petrsvihlik/WopiHost#63]
**Question:** 
>  Is there a way to edit a MS Word or MS Excel document in native MS Windows Office applications? I mean a document, stored on my web server and without involving SharePoint.

The WOPI documentation talks about editing in native apps on Apple iOS and Android and no words about MS Windows. It gives me a hope that it's possible with some "old school" technologies like [MS-FSSHTTP](https://msdn.microsoft.com/en-us/library/dd943623) and Cobalt library (which is not required anymore for Office Online) or may be it works, but only if the native apps are MS Office 365.

P.S. I know, it's not the right place for a such question and a [similar questions was answered](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/8521153b-a255-4255-bc6e-38f356fc4041/edit-documents-with-office-online-wopi) by Microsoft a year ago saying simply "No, it's impossible". But it's just doesn't add up and it's hard to wrap my head around the fact that MS Windows is an outsider here. And judging by your repository, clearly you are a trust-worthy expert here (I guess, with a much higher level of expertise than folks from the MS support).

Thank you for your help in advance.

**Comment by petrsvihlik** [comment]
hi @AKlaus , yes it's possible using WebDAV.

see my answers on stackoverflow:
- https://stackoverflow.com/questions/42717433/cant-save-office-online-wopi-documents-back-to-the-server
- https://stackoverflow.com/questions/37276654/edit-in-word-using-wopi-and-office-online-server/39128813
