### ISSUE TITLE
Microsoft.CobaltCore.dll

### ISSUE THREAD

**Issue by amelkor** [petrsvihlik/WopiHost#64]
So it tells us 

> all references are NuGets

but there is no more Microsoft.CobaltCore package available on nuget. You have to set the reference manually and the dll can be found on a server with sharepoint installed

**Comment by petrsvihlik** [comment]
The license doesn't allow publishing Microsoft.CobaltCore on NuGet. But you can do [this](https://github.com/petrsvihlik/WopiHost#cobalt).
