### ISSUE TITLE
Using onedrive / office 365 as source

### ISSUE THREAD

**Issue by natilux2** [petrsvihlik/WopiHost#99]
How can I set onedrive / office 365 as source

**Comment by petrsvihlik** [comment]
You need to implement your own [`IStorageProvider`](https://github.com/petrsvihlik/WopiHost/blob/master/WopiHost.Abstractions/IWopiStorageProvider.cs) and related interfaces and provide the implementation to the configuration as described at https://github.com/petrsvihlik/WopiHost#configuration


See the example implementation of a file provider interacting with the local filesystem: https://github.com/petrsvihlik/WopiHost/blob/master/WopiHost.FileSystemProvider/WopiFileSystemProvider.cs

**Comment by natilux2** [comment]
I will give a try
